### ISSUE TITLE
Agree the chat flows

### ISSUE THREAD

**Issue by WiseallDeath** [yalla-coop/death#1]
We've currently agreed four flows, I'll add them here so we can sign off the right level for the scope.

**Comment by thejoefriel** [comment]
@WiseallDeath - if you can send those across by end of this week please that'd be great!

**Comment by thejoefriel** [comment]
Hey @WiseallDeath - how are the chat flows and total list of questions? Do you mind sending across please?

Regarding Quick Fire, is it always an either / or format? We feel that would be best and could make it quite fun, but wanted to check as there are two different types of flows from the draft questions we've seen so far.

**Comment by WiseallDeath** [comment]
Hey @thejoefriel 

Few bits here. For the Quick Fire Qs, yeah we've kept it to either or as we agree it's more fun and not too taxing on someone's brain. 

For the structure it needs to be something along the lines of this:

**Sections**

There will be five sections but after the initial interaction, the main interaction will come via four of them only. These are:

  _About you / Intro section_ - This will be the first thing a customer interacts with and will effectively introduce them to the bot, what it's aiming to do and collect some simple information which is largely listed below in the 'Basic info' part of the Profile. After this 'onboarding' the customer won't revisit this section (if that's possible). 
  _Quick Fire Questions_ - These are the 'this or that' questions such as do you prefer jam or Marmite? 
  _Let's Chat_ - This is the central area for most engagement and will cover any questions that require more than an and/or response
  _Record a memory_ - This is specifically for journal-like entries of memories or fascinating things that want to be held for perpetuity. 
  _Message Future Me_ - This is where you can record messages and delivery dates to be delivered to your future self via the email address associated with your account. 

**Profile**
- Basic info:
  Key things really will be
  Name
  Date of Birth/How old you are. 
  Where you live/Home town
  How you identify gender-wise
  Edit/change profile image
  List email address associated with the account.
  Ideally - edit reset password

- Quick Fire responses listed
- Chat responses listed
- Recorded memories - with title, date, content

   Message your Future Self - We will want a bit in there to reference this bit and show it hasn't been forgotten but at most we'll only want to show how many  messages they've sent and little more. We may accompany this with some text that says something like, "We don't show you the details of the messages you've already sent to your future self because we believe it's terrible to spoil surprises."

Does this give you the steer you need right now prior to getting the deeper text over?

Thanks, 
Paul

**Comment by WiseallDeath** [comment]
@thejoefriel I can't grant permissions on this but I've asked Molly to do so and this should be sorted by 9am.
