### ISSUE TITLE
Cancel buttons during flows

### ISSUE THREAD

**Issue by Oliversw** [yalla-coop/death#119]
Often while reviewing and testing I have accidentally clicked on the wrong arrow, but we often don't have the option to cancel a flow, e.g. in the `send a message to yourself` flow. Clicking finish just takes us to the options for when to send it.

**Comment by thejoefriel** [comment]
This is a good point, but I'm going to put bonus on this since it's outside of scope :) 
Currently what the user can do is leave the chat or do a manual refresh and then when they come back it'll be reset to the beginning

**Comment by Oliversw** [comment]
Sounds good! Just trying to throw any usability issues that I find into an issue so we have a record of it. Thanks @thejoefriel!
