### ISSUE TITLE
BUG - Fix alignment on sign up in ipad mobile size

### ISSUE THREAD

**Issue by teenie-quaggard** [yalla-coop/death#122]
Sign up is off-centered (in both Chrome and Mozilla) in sign up, ipad size. Looks kinda strange!

![Screen Shot 2019-08-24 at 12 32 44](https://user-images.githubusercontent.com/37771591/63636766-ac897280-c66b-11e9-91be-00c9c16d6dd0.png)

**Comment by thejoefriel** [comment]
Hmm interesting must be an issue in disparity between the breakpoint for the menu and the breakpoint for the padding?
