### ISSUE TITLE
RESOURCES NEEDED - high quality logo files

### ISSUE THREAD

**Issue by teenie-quaggard** [yalla-coop/death#125]
Hi @WiseallDeath! 
I hope you are well! 

We have been using screenshots of the various DEATH.IO logos as stand-ins for high quality ones in the current version of the app. Could you please send over the high quality versions of those image files so we can replace them? Thank you!

**Comment by thejoefriel** [comment]
Hey @WiseallDeath - just following up on this. Would be good to swap in hi res as at the moment it looks very blurry!

**Comment by WiseallDeath** [comment]
Hey! I missed this one. 

Yeah no worries, I've attached a bunch here. GH won't take the Adobe files though so I'll email separately with the original .ai and .psd files so you can tweak in any way you see fit (within reason #obvs). If you do dip into the original file, note we're only using the .io versions not the two which simply say DEATHio. You'll see what I mean. 

![Deathio_logo_green_Horiz](https://user-images.githubusercontent.com/53015281/64121061-b01ca800-cd95-11e9-8d61-8fc11c984680.png)
![Deathio_logo_white_Horiz](https://user-images.githubusercontent.com/53015281/64121062-b0b53e80-cd95-11e9-8ca2-a9ee3968cccd.png)
