### ISSUE TITLE
Agree database schema

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/death#13]
Please build models and paste in here along with your thinking

**Comment by teenie-quaggard** [comment]
Sorry this is very much a work in progress...
Here's something to get us started.

## Basic user schema:
```
const UserSchema = new mongoose.Schema({
  email: {
    type: String,
    default: '',
  },
  password: {
    type: String,
    default: '',
  },
  isDeleted: {
    type: Boolean,
    default: false,
  },
  signUpDate: {
    type: Date,
    default: Date.now(),
  },
  about: [about],
  thisOrThat: [thisOrThat],
  futureMessage: [futureMessage],
  memories: [memories]
});
```

## About schema
Includes basic user data - this could also just potentially live in the user schema, all subcategories are linked into their own table

```
const AboutSchema = new mongoose.Schema({
  name: {
    type: String,
    default: '',
  },
  gender: {
    type: String,
    default: '',
  },
  dob: {
    type: Date,
    default: Date.now(),
  },
  sexuality: {
    type: String,
    default: '',
  },
  homeTown: {
    type: String,
    default: '',
  },
  family: [family],
  work: [work],
  school: [school],
  hobbies: [hobbies],
  achievements: [achievements],
  passions: [passions],
  politics: [politics],
  other: [other],
});
```

```
const ThisOrThatSchema = new mongoose.Schema({
  applesOrBananas: {
    type: String,
    default: '',
  },
  breakfastOrDinner: {
    type: String,
    default: '',
  }
});
```

**Comment by thejoefriel** [comment]
Hey @teenie-quaggard , so this is a way we've done it across a few projects:

QUESTIONS COLLECTION
const questions = {
  id: String,
  number: Number, // each org has serial questions order
  type: String, // yesno, checkbox, ... 
  text: String,
  hintText: String,
  isJumping: Boolean,  // yes if there is questions to skip based on the answer
  options: [{
    value: String, // yes, no, ... 
    nextQuestion: Number, // self reference
  }],
  orgType: String, // company agency ....,
};

ANSWERS COLLECTION
const answers = {
  question: ref(questions),
  answer: any,
  comment: ref(comments),
  user: ref(user),
  review: ref(review),
};

**Comment by thejoefriel** [comment]
By doing it this way we can store information about the questions so we know how to render them and so on 

So in Nightingale it was like this: 
QUESTION COLLECTION
```
{
  questionType: string // basic info Or daily conversation,
  text: string,
  options: [
    {
      text: string, // if this is null that means this would be an open text
      nextQuestion: ref(question ID),
      isOpenText: boolean, // true if this option is open text (tell me your thoughts)
      weeklyEvent: boolean // true if this option is a weekly event
    }
  ],
  nextQuestion: ref(question ID) // (not required) if the question not required a reply from the user so it will send him the next question (for greeting messages)
}
```

**Comment by thejoefriel** [comment]
I think it's right to split about the About and the Basic User schema - makes it more manageable and arguably they each do different things - one is for the purpose of using the app, and the other is more like answers from interacting with the app

**Comment by othman-shamla** [comment]
Kristina, interesting work but I have a few questions and ideas, I want to share.
* I don't understand why (about) field needs to be an array, I think it should just be an object.
* for storing the questions and answers I think we can do it this way
```
const AboutSchema = new mongoose.Schema({
  name: {
    type: String,
    default: '',
  },
  gender: {
    type: String,
    default: '',
  },
  dateOfBirth: {
    type: Date,
  },
  sexuality: {
    type: String,
    default: '',
  },
  homeTown: {
    type: String,
    default: '',
  },
  dead: {
    type: Boolean,
    default: False,
  },
  dateOfDeath: {
   type: Date,
  },
  answer: [answer], 
});

const answerSchema = new mongoose.Schema({
  text: String,
  question: ref(questions),
});

const questionSchema = new mongoose.Schema({
  text: String,
  primaryType: String, 
  secandaryType: String
});
/*
const question = {
   text: "This is a question?"
  primaryType: 'family',
  secandaryType: 'SIBLINGS',
}
```
I think it's okay to have redundant data in primaryType, secondaryType. cuz there is a small number of questions. hundred? it's small

**Comment by thejoefriel** [comment]
This looks good @othman-shamla - we should also add to the question collection:

- flow (e.g. thisOrThat, aboutMe, storeMemory, futureMsg). This will let us know which flow we should trigger
- nextQuestion (references the ID of another question) - this won't be on every one but for storeMemory and futureMsg where we're not using dialogflow we'll need to know which order to present the questions

**Comment by othman-shamla** [comment]
thanks, joe
the answers and the user have a one to one relation, and because of that there is no need to put it in another collection, and it will be easier to get the data

i agree with you about the question collection

**Comment by thejoefriel** [comment]
Hmm, I think putting answers within the About Me could be confusing in terms of separation of matters. Personally I like About being the core information of each user, and then we have a separate collection of answers they have provided for the various flows. Open to discussing a different way of doing this though. 

I've created the following working with Kristina. I feel this would be a simple way to query but let me know if you want to make different :) 

http://www.clipular.com/posts/6435946772561920?k=PWDR_Nez650qLmS4MudTP3KSxcs
![image](https://user-images.githubusercontent.com/19708921/62125973-8f5cc080-b2c6-11e9-9445-19eecc2efc02.png)

**Comment by othman-shamla** [comment]
yes your right, I will go with reference in memories and futureMessages and Answers collections but not for the about the collection, it's not worth updating two collections when we want to update the profile for the user :p 

but it's cool, we can work with it

but have a question why you put a year, month and day with memories collection and not for the futuremessages as you put dateToSend

**Comment by thejoefriel** [comment]
Haha ok @othman-shamla :) So are you saying you would prefer the about documents within the about collection to be within the users collection?

Re question about year, month, day
So with memories, they may not want to put the exact date, they may just want to put the month or the year. So in the flow, we give them the change to enter the year, then month, then day with them able to skip each section. This offers flexibility in what they enter and we store each as a string. 

For future messages, they get three options on when they want to receive (1 year, 2 year, 3 years) so we simply take the day's date and add the respective number of years, then store in as a specific date

**Comment by othman-shamla** [comment]
@thejoefriel  yes, but cool we can work with this

okay, thanks for answering

**Comment by thejoefriel** [comment]
This is now agreed and being closed

**Comment by thejoefriel** [comment]
Storing the updated version of database schema here 

https://drive.google.com/file/d/1Wo-efmmWVJl84jK5xMive9Ets-RadNDH/view?usp=sharing
