### ISSUE TITLE
Agree on tech stack and eslint 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/death#14]
The current plan so far:

Front-end: React, HTML, CSS, Styled Components
Back-end: Node, Express
Testing: Supertest
Chatbot: Dialogflow

Main things to still agree:
- Database language we want to use
- Testing language (Jest?)

**Comment by teenie-quaggard** [comment]
I am happy with React and Styled Components for the front end.
In terms of Styled Components, I would prefer to keep our imports simple, by importing all of the styles into the file as S and then by accessing each styled component by prefixing the component with ```S.```. For example:

```
import Header from ‘Components/Header’;
import * as S from ‘./styles';
const Navigation = () => (
  <S.Navigation>
    <Header>{headerContent}</Header>
    <S.Content>{content}</S.Content>
  </S.Navigation>
);
```
The style file might look like:
```
import styled from 'styled-components';

export const Navigation = styled.nav`
   //STYLES HERE//
`;

export const Content = styled.main`
   //STYLES HERE//
`;
```

Also, instead of writing a global css file, would everyone be happy to keep everything in Styled Components by using [createGlobalStyle](https://github.com/founders-programme-2/business-launchpad/blob/master/client/src/styles/globalStyle.js) from the Styled Component framework?

I'm happy with Node/Express for the backend.
For database, I would prefer Mongo because I need more practice with it (but happy to try Sequelize if not).

Testing:
Front end testing, I am quite keen to try [React Testing Library](https://testing-library.com/docs/react-testing-library/intro).
Olly and I saw a talk on it the other day and it looks quite cool. 
Happy with Jest - on a quick search, it integrates well with React Testing Library

**Comment by Oliversw** [comment]
I agree with everything that Kristina said! I would also be very happy to work with Mongo again, but  learning Sequelize would be fine too. Everything else looks great to me

**Comment by thejoefriel** [comment]
Yup all happy with this and happy to use Mongo again if that's the common consensus. 

Regarding the styles, sounds good. I'd also suggest we have some usable objects as well (this is what we normally have within our theme.js file) 

```
// colors
export const colors = {
// primary (darkblue)
  primary: "#08294A",
  lightPrimary: "#6C8FB2",

  // negative/error, positive/success
  red: "#EA5254",
  green: "#5BAF93",

  // fontcolors
  fontPrimary: "#07294A",
  fontBlack: "#313234",

  // general
  white: "#FFFFFF",
  grayWhite: "fbfbfb",
  black: "#000000",
}

// shadows
export const shadows = {
  main: "0px 0px 24px rgba(0, 0, 0, 0.04)",
  card: "0px 0px 24px rgba(0, 0, 0, 0.04)",
  pic: "0px 2px 24px rgba(0, 0, 0, 0.215882)"
};

// borders
export const borders = {
  inputBox: `1px solid ${colors.graySecondary}`,
  divider: `1px solid ${colors.lightGray}`,
  lightDivider: "1px solid rgba(0, 0, 0, 0.1)"
};
```

This is incredibly useful for consistency then across the individual style files

**Comment by AsalaKM** [comment]
I agree too with Kristina!
And for the database, I would prefer Mongo again because I need more practice with it (specially work on with aggregation). Everything else looks great!

**Comment by dupreesi** [comment]
I'm fine with all of your suggestions!

**Comment by dupreesi** [comment]
If no one has used the React testing library I'm happy to write an initial test and write up a bit of documentation as I've used it a bit (but am not an expert at all)

**Comment by thejoefriel** [comment]
Also, regarding Navigation, I'd suggest that would actually be one of our Common components? On that point I've created an issue to discuss initial common components:

https://github.com/yalla-coop/death/issues/64

**Comment by othman-shamla** [comment]
Mmmmm
I didn't use the style component before, but I'm happy to learn it. and for the database, I think using MongoDB will be great for this project.

**Comment by Oliversw** [comment]
They're not too hard to learn @othman-shamla! Personally I really love them too. Happy to help with them in any way that I can!

**Comment by thejoefriel** [comment]
Yeah I'll be happy to help as well @othman-shamla :) Once you have one or two in place, they then are really nice and simple

**Comment by thejoefriel** [comment]
OK so we're all agreed on Mongo 👍 and we'll use Mongoose with it. 

From our conversation with @ivanmauricio - can everyone have a look at tailwind and tachyons and see what they like? As he said, they work with Styled Components so it's not something essential and can be just something you try out

**Comment by teenie-quaggard** [comment]
Oh BTW - this is the GUI that Oliver and I used with Mongo

## [MongoDB Compass](https://www.mongodb.com/products/compass)
I think it must be quite similar to Robo 3T. I don't really mind either way.


Will have a look at Tailwind / Tachyons later today.

**Comment by othman-shamla** [comment]
@Oliversw  @thejoefriel  
thanks guys, I think I will have fun learning them, and if I have a question I will contact you

**Comment by teenie-quaggard** [comment]
Just an update on the conversation in stand up today:

We will not be using Tachyeons and will stick to Styled Components as this is already a first for some of us.

We will try to use Dialogflow via post requests, but may use Pusher as a handler for making the connection between Dialogflow and our app if needed.

**Comment by teenie-quaggard** [comment]
Oh! One thing that we haven't spoken about - what are we doing for authentication?

**Comment by thejoefriel** [comment]
For authentication @teenie-quaggard I think the simplest thing is to create out own authentication middleware. Passport isn't necessary for this sort of email password authentication and I think actually over complicates things

What do you think?
