### ISSUE TITLE
BUG: When user changes email to email already existing in database

### ISSUE THREAD

**Issue by teenie-quaggard** [yalla-coop/death#144]
We need to throw a client side error, or else it crashes our backend:
![Screen Shot 2019-08-29 at 11 33 17](https://user-images.githubusercontent.com/37771591/63934484-62c9cf00-ca53-11e9-9afb-1086f0392ae9.png)

**Comment by MohammedYehia** [comment]
@teenie-quaggard try rebuilding the database and see if the error is gone or not because we did some updates on the database
