### ISSUE TITLE
BUG: profile side menu is not tab-able in desktop

### ISSUE THREAD

**Issue by teenie-quaggard** [yalla-coop/death#146]
Ensure left menu is tabable in desktop view

**Comment by MohammedYehia** [comment]
@teenie-quaggard  

![tabable](https://user-images.githubusercontent.com/7594617/63935914-2a33f080-ca67-11e9-9628-9ccc34d443b8.PNG)

**Comment by teenie-quaggard** [comment]
I guess it must be a Firefox issue!

**Comment by MohammedYehia** [comment]
@teenie-quaggard any updates?

**Comment by teenie-quaggard** [comment]
Hi @MohammedYehia !
Do you mind please trying in Firefox on your computer?

**Comment by MohammedYehia** [comment]
![firefox tabbale](https://user-images.githubusercontent.com/7594617/64162467-0518f680-ce48-11e9-9bfc-06937cd10088.PNG)

@teenie-quaggard It is working fine on firefox
so I will close the issue

**Comment by MohammedYehia** [comment]
![firefox tabbale](https://user-images.githubusercontent.com/7594617/64162467-0518f680-ce48-11e9-9bfc-06937cd10088.PNG)

@teenie-quaggard It is working fine on firefox
so I will close the issue
