### ISSUE TITLE
BUG: Render 'what to do next' buttons after user has ended the flow

### ISSUE THREAD

**Issue by teenie-quaggard** [yalla-coop/death#150]
This screenshot is where I am left after I have clicked the button 'I'd rather not say'
This ends the flow, but we need to give the user other options of things to do, and/or link their responses to the appropriate task

![Screen Shot 2019-08-29 at 15 53 46](https://user-images.githubusercontent.com/37771591/63951673-1774e800-ca76-11e9-8b8d-7601be84e216.png)

**Comment by MohammedYehia** [comment]
@teenie-quaggard @thejoefriel I am not sure what should happen here?

**Comment by teenie-quaggard** [comment]
@MohammedYehia - yes please!
