### ISSUE TITLE
BUG: Dates appear close in mobile view (view memory)

### ISSUE THREAD

**Issue by Oliversw** [yalla-coop/death#154]
(Firefox)

The text just needs a little adjustment, or at the very least a `:` between the title and the date

![Screen Shot 2019-08-29 at 10 39 07 AM](https://user-images.githubusercontent.com/9094166/63954893-78d29200-ca49-11e9-81e1-d2c9e6e12188.png)

**Comment by othman-shamla** [comment]
solved by someone and cant find the PR
