### ISSUE TITLE
Add some neutral terms to the yes route (e.g. maybe, not sure, let’s see)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/death#187]
On some of the questions like 'Do you want to be married?' we should add some more neutral terms to the training phrases (e.g. 'Maybe', 'Not sure', 'Let's see') which will still trigger the Yes flow. 

This needs to be done on a case by case basis and just requires someone to go through the flows to decide as and when we add these

**Comment by MohammedYehia** [comment]
done
