### ISSUE TITLE
Work flow is initiating the whole intro messages

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/death#188]
Not sure if this is the work flow or just the first flow after they've gone through onboarding, but for some reason it renders ALL the final onboarding messages when they then choose to answer questions about themselves after they've just finished onboarding. 

Let me know if you can't replicate this and I'll do it and upload a video later.

**Comment by MohammedYehia** [comment]
@thejoefriel It would be great if you could send a video for this issue

**Comment by MohammedYehia** [comment]
got it and fixed 👍
