### ISSUE TITLE
Help tab - to move and become feedback

### ISSUE THREAD

**Issue by WiseallDeath** [yalla-coop/death#205]
The Help tab needs to be changed to feedback and, once clicked, the copy inside adjusted to reflect this. 
The tab also needs to shift elsewhere and I'm happy to be led by you folks. Where it sits right now it's directly above the text send 'paper airplane' and has been repeatedly and accidentally tapped by thumbs in testing. 

Place - General on desktop and mobile

**Comment by MohammedYehia** [comment]
@WiseallDeath I changed its place on mobile so right now it's on the menu screen like this
![new feedback place](https://user-images.githubusercontent.com/7594617/65435701-9a951e00-de29-11e9-9729-56d63601abf6.PNG)
