### ISSUE TITLE
Intro copy loading in wrong flow

### ISSUE THREAD

**Issue by WiseallDeath** [yalla-coop/death#207]
The introduction specific copy needs to load within the intro section but currently appears elsewhere. 

I know a lot of copy isn't uploaded yet and I've avoided most copy specific feedback for the mo, but this intro bit is an error and in the immortal words of Bruce Willis, I don't wanna miss a thing.

**Comment by thejoefriel** [comment]
Hey all yeah just to confirm on this the issue is that the intro text for when a user first signs up sometimes doesn't show up when they first sign up but then appears at the start of another about me flow. This is related I believe to #188

**Comment by MohammedYehia** [comment]
@WiseallDeath Could you explain more about this issue

**Comment by MohammedYehia** [comment]
got it and fixed 👍
