### ISSUE TITLE
Profile pic uploading wrong

### ISSUE THREAD

**Issue by WiseallDeath** [yalla-coop/death#209]
Have had two instances of the profile picture uploading horizontally and then randomly deleting a few minutes later. 
Will try and get a video of this and add to the issue
Placement - Profile, desktop (haven't tested mobile)

**Comment by MohammedYehia** [comment]
@WiseallDeath We are waiting for your video

**Comment by WiseallDeath** [comment]
Hey folks. We haven't been able to replicate it since, so we can't get a video. 
This is probably a positive thing. Need to be sure it's unlikely to happen again though.

**Comment by MohammedYehia** [comment]
I am going to close it now and you can open another issue if the issue pops up again
