### ISSUE TITLE
Tell me about yourself - some responses coming through wrong

### ISSUE THREAD

**Issue by WiseallDeath** [yalla-coop/death#217]
Again, I'm generally avoiding points regarding the copy but this one is a quirk with some responses coming through to the wrong questions. 

Here quite a funny example:
![WhatsApp Image 2019-09-16 at 09 42 02](https://user-images.githubusercontent.com/53015281/65017333-65b33380-d91e-11e9-91b0-c1850a745c89.jpeg)

**Comment by thejoefriel** [comment]
I've looked into this and this is just an error in dialogflow where the wrong copy has been pasted in, so whoever takes on this issue, you just need to update dialogflow

**Comment by MohammedYehia** [comment]
Fixed
