### ISSUE TITLE
Doesn't recognise 'dunno' + middling responses flow

### ISSUE THREAD

**Issue by WiseallDeath** [yalla-coop/death#218]
The responses don't recognise the word dunno. Yeah I know it's not really a word but it came up a few times. One example is when it asks would you like to be married - dunno would be a good response but it doesn't work. 

For these kinds of middling responses we either need to simply skip that bit of the flow or follow the 'No' flow option

**Comment by MohammedYehia** [comment]
Fixed: added the word and followed the no flow
