### ISSUE TITLE
Having signed up in I am greeted by the chatbot who tells me about the app and asks me a few select questions to finish my on boarding process

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/death#22]
This is the onboarding process. Exact dialog flow to be added in comments below.

**Comment by thejoefriel** [comment]
Hey @WiseallDeath - do you mind adding the relevant flow for this onboarding process here please? Thanks! 🙏

**Comment by dupreesi** [comment]
![Bildschirmfoto 2019-08-08 um 13 38 55](https://user-images.githubusercontent.com/23721486/62700362-00e0f100-b9e2-11e9-9a6f-46859c548762.png)
