### ISSUE TITLE
Auto Focus on chat flows filling the page

### ISSUE THREAD

**Issue by WiseallDeath** [yalla-coop/death#220]
On Mobile. 
Maybe less a bug and more a question of UX. 
When you click into a chat flow the auto focus brings up the keyboard which is great, except it fills half the page which when coupled with the rapid fire text above (related to previous issue of pacing on chat flow delivery) no users are able to keep up. 

I can't send a screenshot as it drops the keyboard everytime I try but if you check it out on your mobile you'll see what I mean. 

Fixing the flow pacing may help but it may also be that the auto focus doesn't kick in until a user has clicked to text initially and then from there the AF just keeps the keyboard up. 

Be interested for your thoughts.

**Comment by thejoefriel** [comment]
A couple of things that can be done here:

- Staggering of the bot's messages
- Only trigger auto focus at the point the bot has finished speaking and we're ready for user input
- Make sure text input field is only showing when we actually want the user to enter text
