### ISSUE TITLE
Quick Fire Questions are duplicating

### ISSUE THREAD

**Issue by WiseallDeath** [yalla-coop/death#226]
I've just created a new account and the This or That questions are duplicating. Each one is presented twice before moving onto the next question. 
This is a new error

Screenshot here:
<img width="534" alt="Screenshot 2019-09-18 at 14 49 48" src="https://user-images.githubusercontent.com/53015281/65155045-74840e00-da24-11e9-9572-070bb0e3abeb.png">

**Comment by MohammedYehia** [comment]
@WiseallDeath fixed, please test
