### ISSUE TITLE
Store a Memory chat flow breaking when inputting date

### ISSUE THREAD

**Issue by WiseallDeath** [yalla-coop/death#236]
After putting in the year of a memory the text reverted back to an early point in the Store A Memory text rather than asking for the month.
Image: 
<img width="524" alt="Screenshot 2019-09-27 at 15 13 34" src="https://user-images.githubusercontent.com/53015281/65776456-1b119280-e13a-11e9-87f8-3270df64fab6.png">

**Comment by dupreesi** [comment]
@thejoefriel @WiseallDeath I cannot replicate this bug anymore so might have been fixed. Lets try again once the latest app version is online

**Comment by WiseallDeath** [comment]
Hey Simon, 

Not sure if the latest version is up or not but I just tried it again a moment ago and got the same response. On Desktop this time. 

<img width="1432" alt="Screenshot 2019-10-08 at 11 08 45" src="https://user-images.githubusercontent.com/53015281/66387583-28414380-e9bc-11e9-92d5-75a3a438d63d.png">

**Comment by MohammedYehia** [comment]
@WiseallDeath 
this fixed now
please test
