### ISSUE TITLE
'About me' chat flow doesn't recognise Yes - Movies

### ISSUE THREAD

**Issue by WiseallDeath** [yalla-coop/death#237]
When answering questions about movie preferences the chat flow got lost and didn't recognise a positive response. 
Here's what I had:
![Screenshot_20190927-105128_2](https://user-images.githubusercontent.com/53015281/65776826-c4588880-e13a-11e9-86c2-5e5410932b30.png)

**Comment by MohammedYehia** [comment]
solved
