### ISSUE TITLE
zendesk doesn't work

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/death#254]
clicking on feedback doesn't show anything
check the login details here:
https://docs.google.com/spreadsheets/d/1TO--a_9gZmDRQ5G02f5vFEzUI8OPlU2Y9wrBHuziVi8/edit#gid=0

**Comment by Oliversw** [comment]
Entering the Zendesk url of this project on Zendesk's log in page returns the following error:
```
Oops, this help center no longer exists
The company you're looking for is no longer using our help center. We suggest reaching out to them directly via their official website.
```
Need to confirm account
