### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/death#264]
- [ ] this happens only for some users
- [ ] validation error saying that username/pw are incorrect 
- [ ] using same email to sign up throws an error saying that the email already exists

to test use paul@death.io and pw Crumpetcustard7439

**Comment by dupreesi** [comment]
leaving this for now as it seems to work. think problem will be resolved by re-building the db

**Comment by othman-shamla** [comment]
i think we should use an error logging service or library to save the errors that happen in production and it will save time when we debugging for any error also we can know the source for those type of errors that we couldn't replicate
@dupreesi  @RamyAlshurafa
