### ISSUE TITLE
Forgot password doesn't work

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/death#265]
it says that the email does not exist in the database

**Comment by othman-shamla** [comment]
hey @WiseallDeath 
i need your help on enabling the 2 steps verification in the production email (deathbot.app.io@gmail.com) and please login with the email on your mobile to activate it.

**Comment by WiseallDeath** [comment]
Hey @othman-shamla 
I just went to do that but it turns out it's not my phone number the 2-step is linked to so I can't help - sorry!
@dupreesi @thejoefriel Do either of you know who set up the Deathbot Gmail?

**Comment by othman-shamla** [comment]
thanks Paul, we solve the problem.
