### ISSUE TITLE
As an interested user I can click a link to view a friend’s memories page and sign up

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/death#271]
- [ ] Please refer to wireframes section **ACCESSING MEMORIES**
- [ ]  I can see a landing page with a headline showing me "[name of the friend]'s Memories" an explanation about why I’m asked to create an account
- [ ]  I can choose between the option to log in or sign up (same register user process)
- [ ]  After signing up / logging in I’m getting redirected to the onboarding flow with one extra card

**Further notes:**
- [ ]  for such referal sign ups please add a field to the user model, e.g. 'referral sign up‘ so we know its a referral users
- [ ]  add permission emails array to database schema to check if email has required permissions
- [ ]  these ‚referral sign ups‘ are following the same user privelege logic as standard users: they can see and do everything a ‚normal‘ user can

**Comment by othman-shamla** [comment]
is the referral-sign-up field a Boolean flag or we need to store reference to user who make him sign up

**Comment by dupreesi** [comment]
@othman-shamla good question, lets also store the user that made him sign up to be sure
