### ISSUE TITLE
Stand Up Log (Sprint 1)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/death#3]
In this issue, whenever you've finished a day working on this project, please add a comment answering the following questions:

Date:
What issue(s) did I work on today?
What issue do I plan to work on tomorrow?
Am I facing any blockers?

This is so everyone in the team can be fully aware of what you're working on even when you're not able to make stand ups (e.g on Friday / Sunday) 👍

**Comment by Oliversw** [comment]
Just pinned this so it sits at the top of the issues page so that we (hopefully) don't forget! 😄

**Comment by teenie-quaggard** [comment]
## Date: 
July 30 2019

## What issue(s) did I work on today?
Reviewed #5 
Created global style sheet #15 
Began landing page #71 

## What issue do I plan to work on tomorrow?
I see what's open next week. Feel free to pick up on the landing page if you want.

## Am I facing any blockers?
Only my own 🧠

**Comment by othman-shamla** [comment]
Date:
* July 30 2019

What issue(s) did I work on today?
* setup codeBase issue #5 #7 
* reading about Dialogflow 
* I tried using styledComponent and reading about mongoose

What issue do I plan to work on tomorrow?
* I will do the Travis and codeCov #11 
* setup Heroku #10
* if we finish the agree on the schema #13 I will build the models and the connection

Am I facing any blockers?
* trying to remember how things goes :"D

**Comment by thejoefriel** [comment]
Date:

July 30 2019
What issue(s) did I work on today?

Contributed to discussions on tech stack and DB schema
Setting up Dialogflow #70 

What issue do I plan to work on tomorrow?
Complete #70 once heroku is setup

Am I facing any blockers?
Just the heroku thing :)

**Comment by othman-shamla** [comment]
Date:
July 31 2019

What issue(s) did I work on today?
* working on setup database #75 
* make sure Travis and code coverage work #11 

What issue do I plan to work on tomorrow?
* finishing the setup database #75 
* Happy to work on any issue

Am I facing any blockers?
* finding dummy data for the database :p

**Comment by Oliversw** [comment]
Date:
What issue(s) did I work on today?
- Landing page #71
   - Including button component #72 
- Running through Joe's PR for dialog flow
What issue do I plan to work on tomorrow?
- Potentially common components but happier to work on anything that might be higher priority!
Am I facing any blockers?
Just getting my head around the technical side of everything that needs to be done!

**Comment by Oliversw** [comment]
Date: Wednesday July 31
What issue(s) did I work on today?
- common components #72 
   - began working on the profile menu but got stuck with link/SVG problems
- landing page components #78 

What issue do I plan to work on tomorrow?
- Whatever is the priority come next week

Am I facing any blockers?
- Knowing the appropriate way to combine Links with other elements, e.g. SVGs and buttons

**Comment by Oliversw** [comment]
Date: Sunday August 5th
What issue(s) did I work on today?
- common components #72 
   - finished and made a PR for the profile menu
- worked on main navigation and header #27 
   - created CSS animated toggle button
   - began styling
   - didn't finish, so pushed up an `in-progress` PR so that anyone who wants to finish it before I work again on Wednesday can do so.

What issue do I plan to work on tomorrow?
- Will look into priorities close to the day

Am I facing any blockers?
- Not being sure that I'm not working on the same thing as someone else 🤷‍♂

**Comment by teenie-quaggard** [comment]
Date: Sunday August 5th

What issue(s) did I work on today?
- styled the navigation menu on oliver's pr #85 
     - will look at it again tomorrow as there is a margin that i can't seem to get rid of

- worked on the profile #35, #88 
     - routed remaining pages
     - created basic styled pages for all 4 profile pages

What issue do I plan to work on tomorrow?
- including the header/menu on all the profile pages
- Making API calls from the front-end to populate the profile pages with data

Am I facing any blockers?
- just this margin issue on #85

**Comment by thejoefriel** [comment]
Date: Monday August 5th

What issue(s) did I work on today?

Setting up the initial flows in dialogflow and reviewing pros

will look at it again tomorrow as there is a margin that i can't seem to get rid of

What issue do I plan to work on tomorrow?

Either continue with flows or pick up another issue 

Am I facing any blockers?

Waiting for confirmation on flows from PO

**Comment by othman-shamla** [comment]
Date: Monday August 5th

What issue(s) did I work on today?
* build the basic chat #29 
* build the this or that flow
What issue do I plan to work on tomorrow?
* continue working in the same issue
* happy to work with any issue after finishing the basic chat
Am I facing any blockers?
* I don't think so

**Comment by othman-shamla** [comment]
Date: Tuesday, August 6th

What issue(s) did I work on today?
*  still here #29 

What issue do I plan to work on tomorrow?
* finishing the issue #29
* I am not sure about what's after that but I think to build other flows will be okay for me 

Am I facing any blockers?
* trying to build the query for the questions that the user didn't answer them.

**Comment by teenie-quaggard** [comment]
Date: Tuesday, August 6th

What issue(s) did I work on today?
- fixed header/menu margin error #27 
- tdd backend profile (The Basics) queries / api call #36 
     There is an in progress PR there for anyone to pick up. It includes:
    * a working query test for the database call to fetch data for the 'Basics'
    * a working query to get basic info data from database
    * a broken api call test for the call to fetch data for the 'Basics'
    * Fixed spelling errors in models (mostly user & about)


What issue do I plan to work on tomorrow?
- Helping Oliver with understanding the backend stuff

Am I facing any blockers?
- general Mongo fog 🌫
- and a fat testing fog to boot

**Comment by thejoefriel** [comment]
Date: Tuesday, August 6th

What issue(s) did I work on today?

- added log out feature
- added questions for ThisOrThat, StoreMemory and FutureMessage to database
- modified the DB schema for the above 

Pushed both these up as PRs awaiting approval 

What issue do I plan to work on next?
Back on Death.io coding wise on Monday so will see what issues are available then

Am I facing any blockers?
No

**Comment by Oliversw** [comment]
Date: Wednesday August 7th

What issue(s) did I work on today?
- Reviewing Othman's PR
- #92 continuing Kristina's work 

What issue do I plan on working on next?
- Finish #92 pair programming and then see what's most important to continue with

Am I facing any blockers?
- Got extremely stuck on #92 with some problems with making nested supertest calls

**Comment by MohammedYehia** [comment]
Date: Thursday, August 8th

What issue(s) did I work on today?

- Reviewing Othman's PR
- finishing issue #39 back and front

What issue do I plan on working on next?
- issue #40 

Am I facing any blockers?
- No

**Comment by Oliversw** [comment]
Date: Thursday August 8th

What issue(s) did I work on today?
- Going through part of project with Simon
- #92 continuing Kristina's work. Got the test to pass, but then merging with the master made some of the new tests break

What issue do I plan on working on next?
- Finish #92 

Am I facing any blockers?
- Extremely confused as to why tests that pass on master aren't passing on my branch

**Comment by thejoefriel** [comment]
Date: Monday August 13th

What issue(s) did I work on today?

Did a half day on Death. Picked up the bug #86 and also created the desktop version of the menu and profile menu #87 

What issue do I plan on working on next?
Not sure yet. Will do PR review first potentially 

Am I facing any blockers?
No

**Comment by Oliversw** [comment]
Date:  Monday August 13th half day)

What issue(s) did I work on today?
- Displaying basic info on profile #99

What issue do I plan on working on next?
- #101 display this or that answers on profile

Am I facing any blockers?
Time! Otherwise no. :)

**Comment by Oliversw** [comment]
Date:  Tuesday August 13th (half day)

What issue(s) did I work on today?
- #101 display this or that answers on profile
   - Worked on database call and tests

What issue do I plan on working on next?
- #101 display this or that answers on profile
   - finish tests, connect to frontend, ideally push up today!

Am I facing any blockers?
Nope

**Comment by Oliversw** [comment]
- Keep forgetting standup logs, sorry!!
Date:  Tuesday August 20th (half day)

What issue(s) did I work on today?
- Reviewing #117, #115, #113, #112

What issue do I plan on working on next?
- Will double check project log but maybe displaying memories 

Am I facing any blockers?
Time management with CF-ing, but that's about to get better after tomorrow!

**Comment by Oliversw** [comment]
Date:  Wednesday August 20th (half day)

What issue(s) did I work on today?
- Displaying memories, but I didn't check and see that it was already being worked on 😓 

What issue do I plan on working on next?
- Will double check project log

Am I facing any blockers?
Time management with CF-ing. I will have more time next week and plan to continue working on the project to make up for this week.

**Comment by MohammedYehia** [comment]
Date: Wednesday, August 21st

What issue(s) did I work on today?

- Reviewing and fixing #108 
- Reviewing and fixing conflict in #112 
- Reviewing and fixing #114 
- Reviewing and fixing #117 
- Reviewing and fixing #115 
- Reviewing #117 

What issue do I plan on working on next?
- issue #31 

Am I facing any blockers?

- No
