### ISSUE TITLE
bug when sharing individual memory

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/death#339]
<img width="792" alt="Bildschirmfoto 2020-03-04 um 18 06 07" src="https://user-images.githubusercontent.com/23721486/75904115-e6210e80-5e42-11ea-99e4-47f1cd9e4f05.png">

**Comment by othman-shamla** [comment]
are you talking about this button? 
we don't have sharing individual memory yet
![Screenshot from 2020-03-05 16-05-44](https://user-images.githubusercontent.com/16326221/75989063-3e1b4c00-5efb-11ea-9df5-2c26310f2b12.png)

**Comment by dupreesi** [comment]
@othman-shamla yeah this button: if you create a new memory click save and share and then share individual memory. that;s a feature from the old version which should be still part of this release. so user has 2 sharing options: individual memory (link that anyone can view) and share all memories
