### ISSUE TITLE
create memory: on desktop make pop ups appear on middle of screen

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/death#351]
e.g. title, date... as modal popups in center of screen (only desktop)

**Comment by RamyAlshurafa** [comment]
Hey @dupreesi 
can you explain more?

**Comment by dupreesi** [comment]
@RamyAlshurafa when you are on desktop and ou want to create a new memory... you want to enter a title, click on the input field and a modal appears in the middle of the screen covering the whole screen with the text input in the middle where you can start typing (for accessibility reasons as on desktop its quite hard to see where you are..

**Comment by othman-shamla** [comment]
i don't understand it very well

lets say i'm a user and i want to create a memory in desktop
i will open the page and when i click in title or description it will show a pop with text input to write your text

**Comment by dupreesi** [comment]
@othman-shamla yeah that was the idea. But I agree it might be not the best flow! let me ask him once more if he really wants this and skip this issue for now
