### ISSUE TITLE
Bug: Reset Password flow

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/death#352]
1) Forgot Password -> send two emails instead of 1 
2) click reset password gets you to blank page...

please check

**Comment by othman-shamla** [comment]
1- you just click twice on the send button :"D
my suggestion is we don't wait for sending the email we just showing the message immediately that we send the email.
2- if you mean the link in the email, it work fine for me, if its anther thing please tell me.

by the way it may the cause all of that just is you have slow internet connection, or the gmail API is just slow.

**Comment by dupreesi** [comment]
sounds good @othman-shamla lets do 2 things: make sure the button cannot be clicked twice and also show message right after having clicked the button :)
