### ISSUE TITLE
Bug: Send future message breaks

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/death#371]
clicking send future message to myself breaks as it cannot find the inputfield ref

-> commented out for now in Chat/index

```
  // {
    //   key: Date.now() / Math.random(),
    //   text: 'Send a message to my future self',
    //   action: 'messageFuture',
    // },
```

**Comment by othman-shamla** [comment]
everything fine for me for the future message flow in chat page, need more information like maybe what did you click before you go to the future message flow?
