### ISSUE TITLE
Bug: Firebase files token expires

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/death#372]
after like 1 h we cannot see any more images or recordings. clicking on the GET 400 error links in the console shows this error

--> need to refresh tokens

<img width="761" alt="Bildschirmfoto 2020-03-08 um 03 11 10" src="https://user-images.githubusercontent.com/23721486/76155299-a2e8c900-60ea-11ea-9aa9-0dbf857d6db4.png">

**Comment by othman-shamla** [comment]
when storing files (images, audio) in firebase we have two options
1) public file: here we can use the same link over and over and doesn't have expired time
2) private file: we upload the file to firebase, save the (path/name) of the file, and when we want to send it to a user we need to generate the URL with expert time.

I considered images and audio that associated with memory private files so whenever we need the audio or images we generate the URL from the (path/name saved in database) of the file and the URL should expire after 15 minutes (we can increase that see this file server/helpers/storage.js)
