### ISSUE TITLE
Website Design Inspiration

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/death#4]
Hi @WiseallDeath - do you mind adding in the comments section various websites we should look at over the weekend ahead of starting to build the wireframes next week please?

**Comment by WiseallDeath** [comment]
Cool. We'll aim to do this in the morning.

**Comment by WiseallDeath** [comment]
Okay, here are a bunch of websites that we really like at this end. A common theme seems to be that they animate in great ways upon scrolling which may be a bit much for us at this stage. AM conscious that most of these are chosen largely for aesthetics and I'm not being much help on the overall UX or flow so I can look more into this is that would be helpful. 

Here though, my favourites are the first four, Moonfarmer, Welly, Google AI and Lemonade. 

Moonfarmer https://moonfarmer.com/
Just beautiful. One of the best looking websites I’ve come across in a while. 

Welly: https://www.getwelly.com/
Really neat stuff, lovely animation and very simple. 

Google AI: https://ai.google/
Simple, on-brand, nice graphics

Lemonade: 
https://www.lemonade.com/
Has a good chatbot approach too. 

Mogney 
https://mogney.com/
Visually powerful, really nice to scroll through

Vuybe: 
https://vuybe.co/
Great example of a company with no product but enticing people to join watchlist

Wokine 
https://www.wokine.com/
Just feels cool when you use it. 

Big Data blog 
https://www.thinkful.com/blog/what-is-data-science/
This is a blog post but the subtle CSS animation when you scroll is pretty gorgeous. 

Monzo 
https://monzo.com/
Simply a neat and tidy website
