### ISSUE TITLE
Sometimes warning about losing memory occurs when navigating to preview

### ISSUE THREAD

**Issue by Oliversw** [yalla-coop/death#443]
It has also popped up for me on other pages after I have already left the create new memory page

![Screen Shot 2020-03-27 at 1 54 39 PM](https://user-images.githubusercontent.com/9094166/77763230-a78e0680-7032-11ea-80e1-db9c029425e6.png)

**Comment by dupreesi** [comment]
I'm thinking maybe de-activate the whole warning feature?
