### ISSUE TITLE
check all padding of pages on desktop

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/death#499]
Padding on some page is off. Predominantly the Welcome process and the 'Share memories' pages, particularly on desktop which pushes the content too far down the page and looks weird. The content and 'Next' button should be more central as it was previously.

**Comment by othman-shamla** [comment]
hey @dupreesi,  just to make sure we are in the same page

the content in  `/memories`, `/basics` routes are pushed down as you said, do i need to push them up?
![Screenshot from 2020-04-05 16-54-37](https://user-images.githubusercontent.com/16326221/78500295-3c44e280-775e-11ea-8fce-933362142e74.png)
![Screenshot from 2020-04-05 16-54-52](https://user-images.githubusercontent.com/16326221/78500297-3e0ea600-775e-11ea-9444-9cf84919cefe.png)



and for the onboarding process, the next button looks in center to me 
![Screenshot from 2020-04-05 16-56-12](https://user-images.githubusercontent.com/16326221/78500369-9ba2f280-775e-11ea-83f5-a3e13f29a7f7.png)

**Comment by dupreesi** [comment]
@othman-shamla I think for desktop
- for all profile pages -> push them up 
- for onboarding also push up the whole page wrapper so that the next and radio buttons are not at the bottom of the page (on big screens it looks very odd and the buttons can be hard to find)
- on the success memroy saved page -> push it up, too
