### ISSUE TITLE
Set up project codebase

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/death#5]
- [ ] Set up initial codebase
- [ ] Install initial agreed packages
- [ ] Sort out git ignore file
- [ ] Set up eslint configuration so it works across everyone's editors and let everyone know what set up they need

**Comment by othman-shamla** [comment]
so guys like what the agreed packages?

**Comment by thejoefriel** [comment]
I'd say initially - beyond things like cookie-parser, env2 etc:

back:
- boom (for http error handling)
- bcryptjs

front:
- styled components
- axios

we'll probably use moment across front and back but that can be installed later


To help with set up, we actually have a boilerplate you can use: https://github.com/yalla-coop/react-express-boilerplate

That may save you lots of time! 
I think though it recently has had an issue with dependency vulnerabilities so you may want to make sure everything is updated there

**Comment by thejoefriel** [comment]
@othman-shamla I've just updated that boilerplate to fix the dependency issue, so should be good for you to download and use

**Comment by othman-shamla** [comment]
@thejoefriel 
thanks, man :100:
