### ISSUE TITLE
Cookie banner obscures the 'chat' input 

### ISSUE THREAD

**Issue by WiseallDeath** [yalla-coop/death#501]
The cookie notice blocks the obvious text input for name etc on 'sign up'. Given the size of the desktop space, it's very hard to know what to do when you have to input your details which are 'blanked' out by the cookie notice. We need need a better approach, perhaps the cookies notice fades after 10+ seconds which will occur during the sign up process.

**Comment by othman-shamla** [comment]
@Oliversw @dupreesi @RamyAlshurafa 
any ideas about what we can do here?

**Comment by dupreesi** [comment]
@othman-shamla you can pass a prop to it called acceptOnScroll that just disables it when some start scrolling. then u could pass location prop with 'top' to it, too?
maybe that would work for now? 
https://github.com/Mastermindzh/react-cookie-consent

**Comment by othman-shamla** [comment]
![Screenshot from 2020-04-05 11-36-44](https://user-images.githubusercontent.com/16326221/78470394-e22e2800-7731-11ea-9e8d-7c5d35c99c32.png)

i don't think there is any other options
and the acceptOnScroll can't be helpful in chat page but i will keep it for other pages
so it will work for now yes
