### ISSUE TITLE
About me text to not be bold

### ISSUE THREAD

**Issue by WiseallDeath** [yalla-coop/death#504]
The 'About Me' text is in bold but all other page explainer text isn't in bold, so let's drop About Me text to regular style

**Comment by othman-shamla** [comment]
just to make sure we are in the same page

is the text you want to be normal text is in aboutMe page `/about` 
![Screenshot from 2020-04-05 10-26-42](https://user-images.githubusercontent.com/16326221/78469232-f79e5480-7727-11ea-9185-6c2a1b0baddf.png)

its looks good with other pages

![Screenshot from 2020-04-05 10-30-54](https://user-images.githubusercontent.com/16326221/78469310-9e82f080-7728-11ea-8182-3c160dc94bc2.png)

![Screenshot from 2020-04-05 10-31-05](https://user-images.githubusercontent.com/16326221/78469313-a0e54a80-7728-11ea-91c6-196ffa4b739c.png)

and maybe if feel the word looks weird we can minimize the space between letters a little bit

![Screenshot from 2020-04-05 10-33-49](https://user-images.githubusercontent.com/16326221/78469363-1bae6580-7729-11ea-99e9-9a17ded278d0.png)

**Comment by WiseallDeath** [comment]
Hey Othman, 
Sorry I'm just coming back on this.

It's the text when you haven't added any 'About Me' information yet. It's bold whereas the same text on the other pages is all regular. Screenshot below. 

This isn't a priority, just a cohesive thing. 

<img width="970" alt="Screenshot 2020-04-06 at 01 23 52" src="https://user-images.githubusercontent.com/53015281/78513717-80a7a100-77a5-11ea-9ec4-d37edf4a79d5.png">
