### ISSUE TITLE
Mobile chat on iPad and mobile not usable, needs adjustment 

### ISSUE THREAD

**Issue by WiseallDeath** [yalla-coop/death#505]
Chat and Email Future Self on Ipad and Mobile doesn't work well. Ipad particularly offers a blank page to respond to and no visibility on the text input the user is writing and the mobile experience blurs the visible and the text that's input. 

I don't know how to add screenshots into this but I have some if needed

**Comment by othman-shamla** [comment]
it will be helpful to put screenshot

you click on 'attach files ...' or drag and drop the image 

![Screenshot from 2020-04-05 12-13-25](https://user-images.githubusercontent.com/16326221/78471056-de50d480-7736-11ea-8ea5-fa3cf50edd79.png)

**Comment by WiseallDeath** [comment]
Of course, here are the screenshots. As you can see it's odd visually but the main issue is not being able to see what you are typing. Older people, like my mum, who will be using this on an ipad will really struggle with this, especiallyif writing something important they'll want to check before posting. 

![IMG_0284](https://user-images.githubusercontent.com/53015281/78514145-c36a7880-77a7-11ea-9bdd-4280e2890b34.PNG)

![IMG_0289](https://user-images.githubusercontent.com/53015281/78514148-c6656900-77a7-11ea-9637-577b1c43cfc7.PNG)
