### ISSUE TITLE
3d payment doesn't seem to work

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/death#522]
using a 3d test card works but doesn't add any payment ids to a user (customer / subscription)

**Comment by othman-shamla** [comment]
its working fine when you run the stripe cli for me, and also #519 working fine
here is a video

![test 3d secure for death-io](https://user-images.githubusercontent.com/16326221/82141395-20912980-983e-11ea-9db3-2eb4a970f25f.gif)
