### ISSUE TITLE
Update Content of Future Message section

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/death#528]
- [x] rename user selection to 'Send a message to the future'
- [x] change bot answers to user as in image below (instead of 'Cool. Let's send a message to our future self' -> 'Let's send a message to the future' and so on
- [x] change 'Empty messages are not allowed' to 'It looks like you haven’t typed anything or you need to click return to post your message (just like a text message). Once you’re ready to message the future, then click the Finish button.’
- [x] add additional option to check if another email address should be input instead of the logged in user's email address (only store email address in db for now)-> see image for details 

![Bildschirmfoto 2020-06-08 um 15 14 01](https://user-images.githubusercontent.com/23721486/84034498-b54cfa00-a99a-11ea-980b-633f03aaeb4e.png)

**Comment by dupreesi** [comment]
1.) please make sure only the new answer is being rendered when clicking finish without text input (not empty messages ..)
https://www.loom.com/share/3d26488eba5644e79150e07713e518a5

2.) please make sure emails are validated
![Bildschirmfoto 2020-06-11 um 14 40 50](https://user-images.githubusercontent.com/23721486/84386460-b035b800-abf1-11ea-90dd-e68d399fa7dc.png)

**Comment by othman-shamla** [comment]
1) there is a problem with video
2) what the message you need the bot to replay when the user enter something other than email?

**Comment by dupreesi** [comment]
1.) oh sorry! recorded the wrong tab: 

- [ ]  when clicking on finish without having put in any text it still shows the old "Empty messages are not allowed" message -> should also render the new error message as it already does when hitting enter

2.) just show something like "Please enter a valid email"

3.)  if you could find a way so we don't have to rebuild all of the questions that would be great otherwise all the user answers will be deleted, too. If thats too tricky let me know please and I'll chat to the PO.
