### ISSUE TITLE
Dialogflow Introduction

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/death#62]
Using dialogflow is fun and not complicated but takes a little while to get used to as there is a specific logic to it.
Before the meeting with Ivan this afternoon it'd be good to watch a few videos/ read stuff about how to set up flows and to understand the terminology. You can create an account and just play with it....

Would be good to know about
 
 - intents
 - actions
 - entities
 - fullfilment
 - webhooks 

fulfillments and webhooks are very important for this project as we need to connect the flows to a database setup. This is where you would integrate webhooks as part of a fullfilment.

**Comment by teenie-quaggard** [comment]
## [This 3 part video was quite helpful and covered most of the above](https://www.youtube.com/watch?v=9aHusGxntPw). 👹

**Comment by Oliversw** [comment]
Thank you @dupreesi and @teenie-quaggard!!
