### ISSUE TITLE
Agree initial common components

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/death#64]
We will build this out as we start working on the code, but initially I believe we should have as a baseline:

- Nav (this will be the header & main menu)
- Button 
- Private Route (for authentication purposes)
- ProfileMenu (the footer menu that will sit in the profile section)
- Loading 

Any others?

**Comment by teenie-quaggard** [comment]
Looks good. I would maybe add a ```go back``` button.
![Screen Shot 2019-07-29 at 11 38 05](https://user-images.githubusercontent.com/37771591/62042214-7c2df000-b1f5-11e9-8574-f9cff7c7250f.png)

And MAYBE this type of link (each of the pages in the profile would initially be populated with one of these if the user has not yet spoken to the bot)
![Screen Shot 2019-07-29 at 11 38 40](https://user-images.githubusercontent.com/37771591/62042284-a4b5ea00-b1f5-11e9-8deb-80d104f3a2b2.png)

**Comment by thejoefriel** [comment]
Yeah perfect!

**Comment by thejoefriel** [comment]
I'm going to close this issue now and have created a new issue for Creating the common components: https://github.com/yalla-coop/death/issues/72
