### ISSUE TITLE
Set up Conversation with Senior Dev 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/death#65]
This is just to clarify what we'll be talking about in our conversation with @ivanmauricio later today. Here's the initial list:

- db schema
- maybe show previous dialogflow project to discuss best practice
- Pusher and if we need it
- eslinting set up advice / recommendations

Please add in the comments below if you'd like to talk through anything else 😄

**Comment by Oliversw** [comment]
Sorry @thejoefriel but what is Pusher?

**Comment by thejoefriel** [comment]
@dupreesi will be able to explain more on Pusher!
