### ISSUE TITLE
Set up common components

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/death#72]
Build the common components for everyone to use within the app:

- [x] Nav (this will be the header & main menu)
- [x] Button
- [x] ProfileMenu (the footer menu that will sit in the profile section)
- [x] Loading

NOTE: I've put the PrivateRoute common component within the authentication issue as makes most sense to create that at the point authentication is set up. Issue #20

**Comment by Oliversw** [comment]
Currently working on a button as part of the landing page #71

**Comment by thejoefriel** [comment]
I've added Icon to this. Once this is done we can refactor the home page

**Comment by Oliversw** [comment]
Also @thejoefriel could you please explain what 'loading' is? Is that what the fake loading page that we had talked about introducing when the memory was being saved?
