### ISSUE TITLE
BUG - Fix inputs on Sign Up so that text is not cut off

### ISSUE THREAD

**Issue by teenie-quaggard** [yalla-coop/death#89]
Confirm password placeholder text is cut off.

![Screen Shot 2019-08-05 at 20 41 45](https://user-images.githubusercontent.com/37771591/62490638-ae28ee80-b7c1-11e9-91fa-aae189bf92db.png)
![Screen Shot 2019-08-05 at 20 42 09](https://user-images.githubusercontent.com/37771591/62490639-ae28ee80-b7c1-11e9-8a5e-dc47ecf5ffa0.png)

**Comment by thejoefriel** [comment]
Hey @teenie-quaggard - I can't replicate this issue? It looks like on the screengrab version the width on the input becomes narrow for email address and confirm password? Is this still happening for you? What device(s) is this on?

**Comment by teenie-quaggard** [comment]
Hi Joe!
Yes, still broken for me. I think it's a Mozilla browser thing happening on all mobile sizes.
