### ISSUE TITLE
Update boom package

### ISSUE THREAD

**Issue by Oliversw** [yalla-coop/death#94]
Visited the npm package page to find out about what Boom did and was greeted with this message:
![Screen Shot 2019-08-07 at 4 31 52 PM](https://user-images.githubusercontent.com/9094166/62636165-ee5aaf00-b930-11e9-9585-7e5328f9e18d.png)
Don't know how important this is but figured it was worth mentioning!

**Comment by MohammedYehia** [comment]
it is deprecated and maybe it will suffer some security issue or something in the future
so I think we should move to @hapi/boom before the files number gets bigger
