### ISSUE TITLE
Agreed chat flow content

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/death#96]
Hi @WiseallDeath - we've been discussing this and I know the questions are in the Draw.io in our references issue #2 , but just want it to be written down that these are done and signed off? We'll be putting them into the codebase from tomorrow and will then be tricky for us to make many changes. 

A couple of the things to discuss 

**Onboarding**
There's a bit that says 'we're going to ask you some more questions' - at the moment instead of this, by the time they've given us the key information (name, birthday, hometown etc) we would then end the flow and ask them what they want to do now (i.e. the usual welcome screen for logged in users where they can pick to store memory, send future message etc) 

Is that ok or is there something important we still need to ask them?

**Store a memory**
Here's the suggested copy we'll put in from the bot 

"I can't wait to hear it! OK, let's jot down some memories"

"Remember, these can be about anyone or anything at all. Maybe it's your favourite birthday, your first kiss, or where you hid all that secret treasure."

"Write down as much as you want (think anything from a haiku to a full on epic) and when you're done simply click the Finished button"

USER ENTERS MEMORY

"Great! Now we need to name the memory. What do you want to name it?"

"What year did it happen?" (date picker with skip option)

"What month did it happen?" (date picker with skip option)

"What day did it happen?" (date picker with skip option)\

"Awesome, I'm going to go and store that now."

END

Let me know if you're happy with this! 

**Send a message**
Here's the suggested copy we'll put in from the bot 

"Cool. Let's send a message to our future self"

"This can be about anything. Write down as much as you want and when you're done simply click the Finished button"

USER ENTERS MESSAGE

"Great! Now all we need to do is decide when you want to send it to your future self."
OPTIONS - 1 year, 2 years, 5 years

"Awesome, I'm going to go and store that to my memory bank now."

Let me know if you're happy with all of this Paul :)

**Comment by thejoefriel** [comment]
@wisealldeath just checking we can sign off on the chat content third morning?

**Comment by WiseallDeath** [comment]
Hey Joe,

I had to send the draw.io doc as an attachment via email as I couldn't
update the online version so hopefully that all came through.

I've just seen your update above from yesterday with the additional points
- you'll see in the draw.io doc I'd touched some of the tweaks on the
opener but re the other bits, I love your suggestions and trust you folks
to do the best thing so yes please crack on, I'm happy.

Thanks,
P
